config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: "users#index", as: "authenticated_root"
  end
  root 'homes#index'

  resources :answers, only: [:index, :new, :create]
  resources :questions, only: [:index, :show] do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user

  validates :answer_content, presence: true
  validates :user, presence: true
  validates :question, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :users, through: :answers

  def self.generate_random_unanswered_question(current_user)
    users_answered_questions = current_user.questions
    all_questions = self.all
    unused_questions = all_questions - users_answered_questions
    unused_questions.first
  end
  # def self.set_question_of_the_day
  #   self.where(current_question: true).update_all(current_question: false, fresh: false)
  #   if self.where(fresh: true) != []
  #     self.new_question
  #   else
  #     self.update_all(current_question: false, fresh: true)
  #     self.new_question
  #   end
  # end
  #
  # def self.new_question
  #   new_question = self.where(fresh: true).first
  #   new_question.update!(current_question: true)
  #   new_question.question
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :question
  has_many :answers
  has_many :questions, through: :answers

  def has_answered_current_question?(current_question, current_user)
    current_question.users.include?(current_user)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    # @current_question = Question.find(params[:question_id])
    @answers = Answer.where(question: @current_question)
  end

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.user = current_user
    @answer.question = @question

    if @answer.save
      flash[:notice] = "Question answered"
      redirect_to question_path(@question)
    else
      flash[:error] = @answer.errors.full_messages.join(". ")
      @current_question = Question.find(params[:question_id])
      render "users/index"
    end
  end


  protected

  def answer_params
    params.require(:answer).permit(:answer_content, :user, :question)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    #find question by params and answer by question
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @previous_answered_questions = current_user.questions
    @question = Question.generate_random_unanswered_question(current_user)
    @answer = Answer.new
    @answers = Answer.where(question: @current_question)
  end
end

app/views/answers/_all_answers.html.erb
<div id="all-answers">
  <% @answers.each do |answer| %>
    <%= answer.answer_content %>
  <% end %>
</div>

app/views/answers/index.html.erb
<%=  %>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheWriteStuff</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>

    <nav class="nav-wrapper">
      <a href="/" class="brand-logo">TheWriteStuff</a>
      <section class="top-bar-section">
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <%- if current_user -%>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <%- else -%>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <%- end -%>
        </ul>
      </section>
    </nav>
  </header>
  <main>

    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>
  </main>
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/questions/_answer_question.html.erb
<h3><%= @question.question %></h3>
<%= form_for [@question, @answer] do |f| %>
  <div id="answer-question" class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer_content, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

app/views/questions/_show.html.erb
<p><%= @current_question %></p>

<%= form_for @answer do |f| %>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer_content, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

app/views/questions/index.html.erb
<ul>
  <div class="question-list">
    <% @questions.each do |question| %>
      <li class="card">
        <div class="card-content">
          <span class="card-title"><%= link_to question.question, question_path(question) %></span>
          <% if question.answers != [] %>
            <% preview = question.answers.limit(3) %>
            <% preview.each do |answer| %>
              <p><%= answer.answer_content %></p>
            <% end %>
          <% end %>
        </div>
        <div class="card-action">
          <a href=#><%= question.answers.count %> answers</a>
          <a href=#>0 upvotes</a>
        </div>
      </li>
    <% end %>
  </div>
</ul>

app/views/questions/show.html.erb
<% if current_user != nil && current_user.has_answered_current_question?(@question, current_user) %>
  <ul id="all-answers">
    <% @answers.each do |answer| %>
      <li><%= answer.answer_content %></li>
    <% end %>
  </ul>
<% else %>
  <%= render "questions/answer_question" %>
<% end %>

app/views/users/index.html.erb
<h5>Current question:</h5>
<% if current_user.has_answered_current_question?(@question, current_user) %>
  <%= "Thanks for answering today's question" %>
  <%= render "answers/all_answers" %>
<% else %>
  <%= render "questions/answer_question" %>
<% end %>

<%= link_to "All Questions", questions_path %><br>

<% if current_user.answers != [] %>
  <%= "Previously answered questions:" %>
  <ul>
    <% @previous_answered_questions.each do |question| %>
      <li><%= link_to question.question, question_path(question) %></li>
    <% end %>
  </ul>
<% end %>